##
### Config for Development Environment ###
##
development:
  EsIndexName: "impcomsn-"
  PG:
    adapter: 'postgresql'
    encoding: unicode
    host: 43.241.189.198
    database: ImportToolDb
    ip: 43.241.189.198
    port: 11010
    user: postgres
    password: HtK5AxyaWFgcwCFT
    timeout: 600000
  MYSQL:
    adapter: 'mysql2'
    host: radial-migrationfinal2.czvptg3xkdzu.ap-southeast-2.rds.amazonaws.com
    database: Apollo
    user: radialadmin
    password: n2pDjKFYzMFAzPbX
    timeout: 600000
    port: 3306
  # MYSQL:
  #   adapter: 'mysql2'
  #   host: radial-migation.czvptg3xkdzu.ap-southeast-2.rds.amazonaws.com
  #   database: Apollo
  #   user: radialadmin
  #   password: n2pDjKFYzMFAzPbX
  #   timeout: 600000
  #   port: 3306
  # ES:
  #   url: "http://localhost:9200"
  #   retry_on_faliure: 5
  #   request_time_out: 30
  #   #adapter: :typhoes
  ES:
    host: 'seekdev0.lbh.one'
    port: '443'
    user: 'elastic'
    password: '6nHYWJhv6CbAN3qK'
    scheme: 'https'
     #log: true
    retry_on_failure: 5,
    request_timeout: 30,
 

##
### Config for Production Environment ###
##

production:
  EsIndexName: "impcomsn-"
  MYSQL:
    adapter: 'mysql2'
    host: radial-migation.czvptg3xkdzu.ap-southeast-2.rds.amazonaws.com
    database: Apollo
    user: radialadmin
    password: n2pDjKFYzMFAzPbX
    timeout: 600000
    port: 3306
  PG:
    adapter: 'postgresql'
    encoding: unicode
    host: 43.241.189.198
    database: ImportToolDb
    ip: 43.241.189.198
    port: 11010
    user: postgres
    password: HtK5AxyaWFgcwCFT
    timeout: 600000
  ES:
     host: 'seekdev0.lbh.one'
     port: '443'
     user: 'elastic'
     password: '6nHYWJhv6CbAN3qK'
     scheme: 'https'
     #log: true
     retry_on_failure: 5,
     request_timeout: 30,


##
### Config for Production Environment ###
##

staging:
  EsIndexName: "impcomsn-"
  MYSQL:
    adapter: 'mysql2'
    host: radial-migrationfinal2.czvptg3xkdzu.ap-southeast-2.rds.amazonaws.com
    database: Apollo
    user: radialadmin
    password: n2pDjKFYzMFAzPbX
    timeout: 600000
    port: 3306
    
  # MYSQL:
  #   adapter: 'mysql2'
  #   host: radial-migation.czvptg3xkdzu.ap-southeast-2.rds.amazonaws.com
  #   database: Apollo
  #   user: radialadmin
  #   password: n2pDjKFYzMFAzPbX
  #   timeout: 600000
  #   port: 3306

  PG:
    adapter: postgresql
    encoding: unicode
    database: ImportToolStageDb
    pool: 5
    #url: "DATABASE_URL:postgresql://postgres:4XfVtpxEeszwPjKR@10.0.0.143:11002/ImportToolStageDb"
    url: "DATABASE_URL:postgresql://postgres:4XfVtpxEeszwPjKR@54.66.136.121:11002/ImportToolStageDb"
    host: 54.66.136.121
    user: postgres
    password: 4XfVtpxEeszwPjKR
    port: 11002
    timeout: 600000

  ES:
     hosts: '52.65.89.242'
     port: 11003
     user: 'elastic'
     password: '5jfgPSB4sNeCxnRd'
     #scheme: 'https'
     #log: true
     retry_on_failure: 5
     request_timeout: 30
